name: Release Charm to Edge and Publish Libraries

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - track/**

permissions:
  # Required for all workflows
  security-events: write
  # Only required for workflows in private repositories
  actions: read
  # Write permission needed for the reusable workflow to push git tags
  contents: write

jobs:
  charms-changed:
    runs-on: ubuntu-latest
    outputs:
      auth_changed: ${{ steps.auth-changed-files.outputs.any_modified }}
      chaoscenter_changed: ${{ steps.chaoscenter-changed-files.outputs.any_modified }}
      backend_changed: ${{ steps.backend-changed-files.outputs.any_modified }}
      infrastructure_changed: ${{ steps.infrastructure-changed-files.outputs.any_modified }}
    steps:
      - name: Checkout repository
        if: github.event_name != 'workflow_dispatch'
        uses: actions/checkout@v4
      - name: Determine changed files in the auth charm
        if: github.event_name != 'workflow_dispatch'
        id: auth-changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: auth/**
          files_ignore: |
            README.md
            CONTRIBUTING.md
            INTEGRATING.md
            CODEOWNERS
            LICENSE
            icon.svg
            .gitignore
            .github/**
      - name: Determine changed files in the chaoscenter charm
        if: github.event_name != 'workflow_dispatch'
        id: chaoscenter-changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: chaoscenter/**
          files_ignore: |
            README.md
            CONTRIBUTING.md
            INTEGRATING.md
            CODEOWNERS
            LICENSE
            icon.svg
            .gitignore
            .github/**
      - name: Determine changed files in the backend charm
        if: github.event_name != 'workflow_dispatch'
        id: backend-changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: backend/**
          files_ignore: |
            README.md
            CONTRIBUTING.md
            INTEGRATING.md
            CODEOWNERS
            LICENSE
            icon.svg
            .gitignore
            .github/**
      - name: Determine changed files in the infrastructure charm
        if: github.event_name != 'workflow_dispatch'
        id: infrastructure-changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: infrastructure/**
          files_ignore: |
            README.md
            CONTRIBUTING.md
            INTEGRATING.md
            CODEOWNERS
            LICENSE
            icon.svg
            .gitignore
            .github/**
  release-auth:
    needs: charms-changed
    if: github.event_name == 'workflow_dispatch' || needs.charms-changed.outputs.auth_changed == 'true'
    uses: canonical/observability/.github/workflows/charm-release.yaml@v2
    secrets: inherit
    with:
      default-track: dev
      charm-path: auth
      git-tag-prefix: auth-
  release-chaoscenter:
    needs: charms-changed
    if: github.event_name == 'workflow_dispatch' || needs.charms-changed.outputs.chaoscenter_changed == 'true'
    uses: canonical/observability/.github/workflows/charm-release.yaml@v2
    secrets: inherit
    with:
      default-track: dev
      charm-path: chaoscenter
      git-tag-prefix: chaoscenter-
  release-backend:
    needs: charms-changed
    if: github.event_name == 'workflow_dispatch' || needs.charms-changed.outputs.backend_changed == 'true'
    uses: canonical/observability/.github/workflows/charm-release.yaml@v2
    secrets: inherit
    with:
      default-track: dev
      charm-path: backend
      git-tag-prefix: backend-
  release-infrastructure:
    needs: charms-changed
    if: github.event_name == 'workflow_dispatch' || needs.charms-changed.outputs.infrastructure_changed == 'true'
    uses: canonical/observability/.github/workflows/charm-release.yaml@v2
    secrets: inherit
    with:
      default-track: dev
      charm-path: infrastructure
      git-tag-prefix: infrastructure-
  release-terraform:
    needs:
      - release-auth
      - release-chaoscenter
      - release-backend
      - release-infrastructure
    if: always() && (needs.release-auth.result == 'success' || needs.release-chaoscenter.result == 'success' || needs.release-backend.result == 'success' || needs.release-infrastructure.result == 'success')
    uses: canonical/observability/.github/workflows/terraform-release.yaml@v2
    secrets:
      OBSERVABILITY_NOCTUA_TOKEN: ${{ secrets.OBSERVABILITY_NOCTUA_TOKEN }}
    with:
      terraform-tag-prefix: tf-litmus-
