name: Tiobe TiCS Analysis

on:
    workflow_dispatch:
    schedule:
    - cron: "0 0 * * 1"  # Runs at midnight UTC every Monday
jobs:
    tiobe-scan:
        name: TiCs
        uses: canonical/observability/.github/workflows/charm-tiobe-scan.yaml@v1
        with:
            tiobe-project-name: litmus-operators
            coverage-folder: coverage
        secrets: inherit