name: Tiobe TiCS Analysis

on:
    workflow_dispatch:
    schedule:
    - cron: "0 0 * * 1"  # Runs at midnight UTC every Monday
    # DO NOT MERGE: here only to test the workflow
    pull_request:
        branches:
        - main
jobs:
    tiobe-scan:
        name: TiCs
        uses: canonical/observability/.github/workflows/charm-tiobe-scan.yaml@v1
        with:
            tiobe-project-name: litmus-operators
        secrets: inherit