name: Auto-update Charm Libraries
on:
  # Manual trigger
  workflow_dispatch:
  # Check regularly the upstream every four hours
  schedule:
    - cron: "0 0,4,8,12,16,20 * * *"

jobs:
  update-lib-auth:
    name: Check libraries
    uses: canonical/observability/.github/workflows/charm-update-libs.yaml@v1
    secrets: inherit
    with:
      charm-path: auth
  update-lib-chaoscenter:
    name: Check libraries
    uses: canonical/observability/.github/workflows/charm-update-libs.yaml@v1
    secrets: inherit
    with:
      charm-path: chaoscenter
